// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type RegisterStudentInput struct {
	FirstName  string `json:"firstName"`
	MiddleName string `json:"middleName"`
	LastName   string `json:"lastName"`
	Gender     string `json:"gender"`
	Email      string `json:"email"`
	Avatar     string `json:"avatar"`
	GradeLevel string `json:"gradeLevel"`
	Section    string `json:"section"`
}

type Student struct {
	StudentID  string `json:"student_id"`
	FirstName  string `json:"firstName"`
	MiddleName string `json:"middleName"`
	LastName   string `json:"lastName"`
	Gender     string `json:"gender"`
	Email      string `json:"email"`
	Avatar     string `json:"avatar"`
	GradeLevel string `json:"gradeLevel"`
	Section    string `json:"section"`
}
